### ISSUE TITLE
能生成彩色的图片吗，我发现生成的都是黑白的

### ISSUE THREAD

**Issue by afterimagex** [oh-my-ocr/text_renderer#11]
能生成彩色的图片吗，我发现生成的都是黑白的

**Comment by xxxpsyduck** [comment]
Definitely. In the demo gif you can see color texts

**Comment by Sanster** [comment]
@afterimagex 把 RenderCfg 的 [gray 参数设置成 False](https://github.com/oh-my-ocr/text_renderer/blob/master/example_data/example.py#L105)，默认使用 [SimpleTextColorCfg](https://github.com/oh-my-ocr/text_renderer/blob/fac07b3e82c49c9e8e5ff64fe994a8ca05e5c4e0/text_renderer/corpus/corpus.py#L44) 生成字体的颜色，里面基本上是随机获得取各通道颜色，你也可以自己实现下取字体颜色的策略
