### ISSUE TITLE
求问为什么载入原始config会RE啊

### ISSUE THREAD

**Issue by simbadu1999** [oh-my-ocr/text_renderer#14]
报错RuntimeError: Load configs failed: example_data/example.py  谢谢

**Comment by Sanster** [comment]
有更详细的错误信息么

**Comment by simbadu1999** [comment]
感谢您的回复，老版本那个我已经复现啦，想请问下新老版本有什么区别啊，谢谢
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "oh-my-ocr/text_renderer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月2日(星期六) 中午1:42
收件人:&nbsp;"oh-my-ocr/text_renderer"<text_renderer@noreply.github.com&gt;;
抄送:&nbsp;"simba"<2078332241@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [oh-my-ocr/text_renderer] 求问为什么载入原始config会RE啊 (#14)





 
有更详细的错误信息么

**Comment by Sanster** [comment]
- 新版本的设计更模块话，扩展起来比较方便
- 新版生成的数据是变长的

**Comment by simbadu1999** [comment]
收到 谢谢


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "oh-my-ocr/text_renderer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月3日(星期天) 中午12:59
收件人:&nbsp;"oh-my-ocr/text_renderer"<text_renderer@noreply.github.com&gt;;
抄送:&nbsp;"simba"<2078332241@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [oh-my-ocr/text_renderer] 求问为什么载入原始config会RE啊 (#14)





  
新版本的设计更模块话，扩展起来比较方便
 
新版生成的数据是变长的
