### ISSUE TITLE
Can not filter wrong chars in Chinese font file. Please help.

### ISSUE THREAD

**Issue by yueshiyi** [oh-my-ocr/text_renderer#24]
![000000003](https://user-images.githubusercontent.com/27753146/119294545-48a03d80-bc87-11eb-8614-61b98aa58f64.jpg)
Label for the above image is “000000003.jpg 马来见 12 12 107 60”, but there are two wrong characters in generated image。Please help.

**Comment by Sanster** [comment]
Please upload the font file to help locate the problem

**Comment by yueshiyi** [comment]
font file: https://pan.baidu.com/s/1gPUaTmhJM4wCLFgyDdXCPA  
code: 9y9v 
Thx.

**Comment by Sanster** [comment]
There are something wrong with your font file. You can use [fonteditor](https://github.com/ecomfe/fonteditor) to check

![image](https://user-images.githubusercontent.com/3998421/119448296-b0c45180-bd63-11eb-9ede-c18bd7242412.png)

方正仿宋.ttf
![image](https://user-images.githubusercontent.com/3998421/119448401-dd786900-bd63-11eb-95d1-de41b84f1876.png)

**Comment by yueshiyi** [comment]
Thanks. That helps a lot.
