### ISSUE TITLE
lmdb2img  Compatible with PaddleOCR 

### ISSUE THREAD

**Issue by chccc5** [oh-my-ocr/text_renderer#25]
step:
1. generated  lmdb file**data.mdb lock.mdb**
```python
python main.py  --config example_data\example.py --dataset lmdb  --num_processes 2 --log_period 50
```

---------------------------
*but* How to convert Compatible with **PaddleOCR**?
is this right？
````python
python tools/lmdb2img.py  inputfiles1  outputfiles2

````

**Comment by Sanster** [comment]
paddleocr supports lmdb dataset https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/recognition_en.md#data-preparation

**Comment by chccc5** [comment]
Why generate 5000 images will generate 1t memory?   Can LMDB format be used in paddleocr?




-------------------------------------------------------------------







At 2021-07-02 08:56:18, "Qing" ***@***.***> wrote:

paddleocr supports lmdb dataset https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/recognition_en.md#data-preparation
