### ISSUE TITLE
How to keep the background image size?

### ISSUE THREAD

**Issue by wendaogongyi** [oh-my-ocr/text_renderer#28]
The generated image size automatically adapts to characters, but I want to keep the original size of the background. How to keep the background size?  How to change the generated image background size?

**Comment by Sanster** [comment]
Background of generated image is randomly cropped from bg image. You can change image height   https://github.com/oh-my-ocr/text_renderer/blob/01375e44d9417ac163d424fbae775c62f57bafd7/text_renderer/config/__init__.py#L146

**Comment by wendaogongyi** [comment]
Thank you for the answer. But I want to keep the original bg image like this picture. Can I change the size of cropped area?
![Inkedbackground_LI](https://user-images.githubusercontent.com/63837576/125376079-d0b7df00-e3bc-11eb-95c0-85c7c5d82955.jpg)

**Comment by wendaogongyi** [comment]
https://github.com/oh-my-ocr/text_renderer/blob/01375e44d9417ac163d424fbae775c62f57bafd7/text_renderer/render.py#L205
Now I can change the cropped area, but the generated image will be fuzzy if I enlarge the cropped area. How can I keep the image clear while the cropped area is big? I want to make the effect like the pictures.
