### ISSUE TITLE
reverse_color

### ISSUE THREAD

**Issue by kingwpf** [oh-my-ocr/text_renderer#3]
Hi, did reverse_color is supported in this version?

**Comment by Sanster** [comment]
No. But it's easy to do this by adding a [Effect](https://oh-my-ocr.github.io/text_renderer/effect/index.html)  and set as [RenderCfg. render_effects](https://oh-my-ocr.github.io/text_renderer/config.html#text_renderer.config.RenderCfg). We recommend adding this data to your training to enhance the effect.

**Comment by kingwpf** [comment]
> No. But it's easy to do this by adding a [Effect](https://oh-my-ocr.github.io/text_renderer/effect/index.html) and set as [RenderCfg. render_effects](https://oh-my-ocr.github.io/text_renderer/config.html#text_renderer.config.RenderCfg).
> 
> However it's recommend to add reverse_color effect as image augmentation in your training.

got it, thanks.
