### ISSUE TITLE
Can I customize the content of the generated json file？

### ISSUE THREAD

**Issue by wendaogongyi** [oh-my-ocr/text_renderer#30]
I want to turn the generated json file into the annotation file of COCO dataset like the picture.
![v2-99cecf64beeab92d5d67f31c4de35c54_720w (2)](https://user-images.githubusercontent.com/63837576/125914696-147d3cf2-75ea-46a5-b24a-240dabd23014.jpg)
Can I customize the content of the generated json file？

**Comment by Sanster** [comment]
Convert format after generation finish
