### ISSUE TITLE
There are several masks on the same generated picture

### ISSUE THREAD

**Issue by wendaogongyi** [oh-my-ocr/text_renderer#31]
I want  one bg to one mask, but there are several masks on the same generated picture. I dont know why, the bg is enough.

**Comment by Sanster** [comment]
what is mask? Please give an example

**Comment by wendaogongyi** [comment]
like the picture
![3words](https://user-images.githubusercontent.com/63837576/127169105-64f42829-e221-44e8-988c-00fd72cd6ccc.jpg)
3 random words appeared on the same picture, but under normal circumstances, 1 random word appeard on 1 picture. I don't know why several words appeared on the same picture. I think maybe the the number of background pictures is too small. But I checked that the number of background pictures is more than the number of generated images.

**Comment by wendaogongyi** [comment]
I found that I set the file incorrectly, and now it's OK. Thanks
