### ISSUE TITLE
关于生成图片中文本的颜色

### ISSUE THREAD

**Issue by ShulinHE** [oh-my-ocr/text_renderer#34]
请问我想生成白色的文本，但是好像没有成功，是为什么呢？
我在example.py的基础上改动了：
def base_cfg(
    name: str, corpus, corpus_effects=None, layout_effects=None, layout=None, gray=True
):
    return GeneratorCfg(
        num_image=50,
        save_dir=OUT_DIR / name,
        render_cfg=RenderCfg(
            bg_dir=BG_DIR,
            perspective_transform=perspective_transform,
            gray=gray,
            layout_effects=layout_effects,
            layout=layout,
            corpus=corpus,
            corpus_effects=corpus_effects,
            text_color_cfg=FixedTextColorCfg(),  # SimpleTextColorCfg(),
        ),
    )
并且把FixedTextColorCfg改了：
class FixedTextColorCfg(TextColorCfg):
    # For generate effect/layout example
    def get_color(self, bg_img: PILImage) -> Tuple[int, int, int, int]:
        alpha = 255
        text_color = (255, 255, 255, alpha)

        return text_color

**Comment by Sanster** [comment]
生成出来是什么样的？

**Comment by ShulinHE** [comment]
大概是这样的
<img width="606" alt="show" src="https://user-images.githubusercontent.com/60364180/129130372-cafb15ea-a38f-4b29-844d-00fecc04597d.PNG">

**Comment by Sanster** [comment]
RenderCfg 的 text_color_cfg 优先级比 CorpusCfg 低，修改 CorpusCfg 的配置

![image](https://user-images.githubusercontent.com/3998421/129161138-8f94e318-ea12-44b4-8703-f2d7f1e4c2a3.png)

**Comment by Sanster** [comment]
https://github.com/oh-my-ocr/text_renderer/blob/master/example_data/example.py#L73
