### ISSUE TITLE
这个配置不大懂啊

### ISSUE THREAD

**Issue by shankslee2021** [oh-my-ocr/text_renderer#35]
我想要一个配置，功能如下
白色和红色字体
padding
字体黑色边框

这个应该怎么配置

**Comment by shankslee2021** [comment]
模糊的开关在哪里啊 能不能给回个话啊

**Comment by ZaneCode6574** [comment]
> 模糊的开关在哪里啊 能不能给回个话啊

先学会如何礼貌问问题再说别的吧
