### ISSUE TITLE
生成的图片有多余空格

### ISSUE THREAD

**Issue by HenrySZP** [oh-my-ocr/text_renderer#36]
你好，我这边使用textrender的时候发现一个问题，就是我给的文本标签里面没有空格，而生成的图片中随机的会有一些空格（几张图片中会有那么一张），请问这是什么原因呢？

**Comment by Sanster** [comment]
字体文件支持的字符是有限的，text_renderer 会[检查字体支持的字符](https://github.com/oh-my-ocr/text_renderer/blob/master/text_renderer/font_manager.py#L65)，遇到不支持的字符不会进行渲染，但是有些字体文件，cmap 里面包含的字符却不能正确渲染，表现为「图片上生成空格」或者「图片上生成乱码的字符」等问题，text_renderer 也会做一定的[检查](https://github.com/oh-my-ocr/text_renderer/commit/79895d20d21c12f0b81e1e5162ee0465e10bed72)，这需要你的 corpus 配置 `chars_file `，你可以试试。还是不行的话，就只能检查下字体了

**Comment by HenrySZP** [comment]
@Sanster 明白了，谢谢解答~

**Comment by thesby** [comment]
设置 char_spacing
