### ISSUE TITLE
设置文字大小失败

### ISSUE THREAD

**Issue by Atiuiee** [oh-my-ocr/text_renderer#38]
我想生成一批大小1000*1000左右的图片，在设置font_size这个参数时，发现它并不能明显改变文字大小，改变的是清晰度
值越小，越模糊，值越大，越清晰
请问怎么修改文字大小呀
另外我需要生成多行文字，求指教

**Comment by Sanster** [comment]
https://github.com/oh-my-ocr/text_renderer/issues/16
