### ISSUE TITLE
用于生成图片的文本文件设置

### ISSUE THREAD

**Issue by GivanTsai** [oh-my-ocr/text_renderer#39]
你好，请问下example_data/text文件下的txt文件，每一行文字生成一张图片，比如
aaaaaaaa
bbbbbbb

应该怎么设置呢，这个txt文件已经生成好了；

**Comment by Sanster** [comment]
使用 EnumCorpus：https://oh-my-ocr.github.io/text_renderer/corpus/enum_corpus.html

**Comment by GivanTsai** [comment]
> 使用 EnumCorpus：https://oh-my-ocr.github.io/text_renderer/corpus/enum_corpus.html

感谢回答，我也找到了这个，这个好像是随机选择的，比如说100条文本行生成100张图片，用这种方法生成的100张图片是不是又重复的呀，类似于放回式抽样？

**Comment by Sanster** [comment]
是的，想要其它行为的话可以自己是实现新的 corpus
