### ISSUE TITLE
多行文字的图像生成

### ISSUE THREAD

**Issue by GivanTsai** [oh-my-ocr/text_renderer#43]
请问下目前可以支持生成具有多行文本的图片吗，或者有什么思路可以实现的吗

**Comment by Sanster** [comment]
可以参考 [extra_text_line.py](https://github.com/oh-my-ocr/text_renderer/blob/master/text_renderer/layout/extra_text_line.py) 中的实现。

这个类是用来生成下图中的效果的：
![image](https://user-images.githubusercontent.com/3998421/159833644-bb7bea7b-7377-4052-98fb-19f65a3ae7c3.png)
