### ISSUE TITLE
关于产生图片txt标签

### ISSUE THREAD

**Issue by zcswdt** [oh-my-ocr/text_renderer#6]
您好，谢谢开源您的研究成果。我下载了您的代码，根据您提供的命令进行了生成图片，但是标签都是json文件，请问可以生成txt标签吗？

**Comment by Sanster** [comment]
目前不支持，你可以自己实现下 txt 格式的 Dataset https://github.com/oh-my-ocr/text_renderer/blob/master/text_renderer/dataset.py#L10

**Comment by zcswdt** [comment]
> 目前不支持，你可以自己实现下 txt 格式的 Dataset https://github.com/oh-my-ocr/text_renderer/blob/master/text_renderer/dataset.py#L10
谢谢指导，我发现另一个问题，在您的字体颜色生成方面，采用的是计算背景图片的均值，根据这个均值的0.7倍来进行颜色选择，当均值越接近255的时候，字体颜色和背景颜色越能区分开，当均值接近0的时候，这个时候字体颜色和背景颜色基本重合。不知道我有没有正确理解这里的代码。https://github.com/oh-my-ocr/text_renderer/blob/550c209e7677116d37a0675e00620090bbe43a07/text_renderer/render.py#L193

**Comment by Sanster** [comment]
0的话是文字的颜色越黑，是否能和背景区分要看背景的颜色了

**Comment by zcswdt** [comment]
> 0的话是文字的颜色越黑，是否能和背景区分要看背景的颜色了

对，假设背景是黑色的话，生成的文字就很接近黑色，背景颜色和文字颜色重合，这样生成的图片就不太适合训练。

**Comment by Sanster** [comment]
是的，这里取文字颜色的策略比较简单，所以留了个接口可以实现不同取颜色的策略。实际操作中，一个是背景图要挑一下，一般有问题的样本不会很多，对训练影响不大，然后模型训到一定程度可以过一遍训练集，把异常样本挑出来

**Comment by zcswdt** [comment]
> 以过一遍训练集，把异常样本挑出来

好的，谢谢耐心回复，明白了。
