### ISSUE TITLE
生成图片固定宽度

### ISSUE THREAD

**Issue by yunWJR** [oh-my-ocr/text_renderer#8]
你好！请问可以设定生成的图片为固定宽度么？

**Comment by yunWJR** [comment]
通过修改 paste_text_mask_on_bg 方法实现了

**Comment by hepei03** [comment]
> 通过修改 paste_text_mask_on_bg 方法实现了

你好! 我也碰到了这个问题, 可以请问一下是具体怎么修改的吗?
