### ISSUE TITLE
字体颜色

### ISSUE THREAD

**Issue by sevenold** [oh-my-ocr/text_renderer#9]
> 请问下关于设置或者获取字体颜色，有没有更好的解决方案？

### 比如
![paper](https://user-images.githubusercontent.com/41443157/98194450-69f34380-1f5a-11eb-8f3e-8cd872aedbf6.png)
### 生成效果
![image](https://user-images.githubusercontent.com/41443157/98194482-7aa3b980-1f5a-11eb-84b6-cc2ee4a10696.png)

> 如果我想生成黑底白字呢，就是和背景相差比较大的字体颜色，有没有什么建议？谢谢！

**Comment by Sanster** [comment]
1. 生成白底黑字，实现一个 [Effect](https://oh-my-ocr.github.io/text_renderer/effect/index.html) 转一下颜色

或者

2. 生成白底黑字，在训练阶段做数据增强时反色（推荐）
